#=================================================
#   Description: Build X-WRT using GitHub Actions
#   Lisence: MIT
#   Author: ptpt52
#=================================================

name: Build Jobs 25.04_b202504130929

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Create Github Release
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-24.04
    steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        name: X-WRT ${{ github.ref_name }}
        draft: false
        allowUpdates: true
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v4
      with:
        name: release_url
        path: release_url.txt
  build-ath79-generic_ath79-generic-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ath79-generic ath79-generic-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ath79-generic_ath79-generic-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ath79-generic
      id: asset-4b6f8478421e012129d8ea91008f7f6a
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ath79-generic.zip
        asset_name: x-wrt-25.04_b202504130929-ath79-generic.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ath79-generic-nosymbol
      id: asset-9b6de008a15c2b5c3186f8c8040550fc
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ath79-generic-nosymbol.zip
        asset_name: x-wrt-25.04_b202504130929-ath79-generic-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-ath79-nand:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ath79-nand" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ath79-nand
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ath79-nand
      id: asset-d1baac840cbed4164c6e8e8d15f19542
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ath79-nand.zip
        asset_name: x-wrt-25.04_b202504130929-ath79-nand.zip
        asset_content_type: application/zip
        overwrite: true
  build-ipq40xx-generic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ipq40xx-generic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ipq40xx-generic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ipq40xx-generic
      id: asset-39f50cf98b07f46b732c080e2b250108
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ipq40xx-generic.zip
        asset_name: x-wrt-25.04_b202504130929-ipq40xx-generic.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2709:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2709" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2709
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-bcm27xx-bcm2709
      id: asset-8840fa2e160ca4bbd689b7c5f155ddc1
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-bcm27xx-bcm2709.zip
        asset_name: x-wrt-25.04_b202504130929-bcm27xx-bcm2709.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2710:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2710" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2710
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-bcm27xx-bcm2710
      id: asset-29362c2ec1858cbb694ed2272e1cbea3
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-bcm27xx-bcm2710.zip
        asset_name: x-wrt-25.04_b202504130929-bcm27xx-bcm2710.zip
        asset_content_type: application/zip
        overwrite: true
  build-mediatek-mt7622:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mediatek-mt7622" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mediatek-mt7622
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-mediatek-mt7622
      id: asset-f54bb9385ff927b505e4962c69403767
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-mediatek-mt7622.zip
        asset_name: x-wrt-25.04_b202504130929-mediatek-mt7622.zip
        asset_content_type: application/zip
        overwrite: true
  build-mediatek-filogic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mediatek-filogic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mediatek-filogic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-mediatek-filogic
      id: asset-032a57f8d67739278af1ae28d6464675
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-mediatek-filogic.zip
        asset_name: x-wrt-25.04_b202504130929-mediatek-filogic.zip
        asset_content_type: application/zip
        overwrite: true
  build-mediatek-filogic-uncommon:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mediatek-filogic-uncommon" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mediatek-filogic-uncommon
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-mediatek-filogic-uncommon
      id: asset-5ac91afa844696a293c95d9b8aaac1cc
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-mediatek-filogic-uncommon.zip
        asset_name: x-wrt-25.04_b202504130929-mediatek-filogic-uncommon.zip
        asset_content_type: application/zip
        overwrite: true
  build-qualcommax-ipq807x_qualcommax-ipq60xx:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="qualcommax-ipq807x qualcommax-ipq60xx" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-qualcommax-ipq807x_qualcommax-ipq60xx
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-qualcommax-ipq807x
      id: asset-259751f1f922eb61a133acba26568db7
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-qualcommax-ipq807x.zip
        asset_name: x-wrt-25.04_b202504130929-qualcommax-ipq807x.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504130929-qualcommax-ipq60xx
      id: asset-3c752ddbf4dbc70ebe11677200ba03dc
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-qualcommax-ipq60xx.zip
        asset_name: x-wrt-25.04_b202504130929-qualcommax-ipq60xx.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2711:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2711" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2711
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-bcm27xx-bcm2711
      id: asset-4cd28caf7c0c66677a71467b96f95e06
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-bcm27xx-bcm2711.zip
        asset_name: x-wrt-25.04_b202504130929-bcm27xx-bcm2711.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2712:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2712" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2712
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-bcm27xx-bcm2712
      id: asset-11281fbc67bc8b9ca814a3aaa66f7e6e
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-bcm27xx-bcm2712.zip
        asset_name: x-wrt-25.04_b202504130929-bcm27xx-bcm2712.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm53xx-generic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm53xx-generic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm53xx-generic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-bcm53xx-generic
      id: asset-3d6dc311ddd2c3cf7198520a6a11e7f6
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-bcm53xx-generic.zip
        asset_name: x-wrt-25.04_b202504130929-bcm53xx-generic.zip
        asset_content_type: application/zip
        overwrite: true
  build-ipq806x-generic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ipq806x-generic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ipq806x-generic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ipq806x-generic
      id: asset-d6442bb8875b56610d1420a78a1d2d76
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ipq806x-generic.zip
        asset_name: x-wrt-25.04_b202504130929-ipq806x-generic.zip
        asset_content_type: application/zip
        overwrite: true
  build-mvebu-cortexa9:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mvebu-cortexa9" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mvebu-cortexa9
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-mvebu-cortexa9
      id: asset-393019f0bba84dd2287621455121e9fb
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-mvebu-cortexa9.zip
        asset_name: x-wrt-25.04_b202504130929-mvebu-cortexa9.zip
        asset_content_type: application/zip
        overwrite: true
  build-ramips-mt7620_ramips-mt7620-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ramips-mt7620 ramips-mt7620-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ramips-mt7620_ramips-mt7620-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ramips-mt7620
      id: asset-a176d8077f0eaccd6fa853eb2e1c908a
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ramips-mt7620.zip
        asset_name: x-wrt-25.04_b202504130929-ramips-mt7620.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ramips-mt7620-nosymbol
      id: asset-6d65aca99faaaad77c5c0917f2a16fbe
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ramips-mt7620-nosymbol.zip
        asset_name: x-wrt-25.04_b202504130929-ramips-mt7620-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-ramips-mt7621_ramips-mt7621-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ramips-mt7621 ramips-mt7621-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ramips-mt7621_ramips-mt7621-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ramips-mt7621
      id: asset-2761398670d0dba838276e4bd27f0cc4
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ramips-mt7621.zip
        asset_name: x-wrt-25.04_b202504130929-ramips-mt7621.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ramips-mt7621-nosymbol
      id: asset-a10e33e69e41cbd865d459eb69e13d52
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ramips-mt7621-nosymbol.zip
        asset_name: x-wrt-25.04_b202504130929-ramips-mt7621-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-ramips-mt76x8_ramips-mt76x8-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ramips-mt76x8 ramips-mt76x8-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ramips-mt76x8_ramips-mt76x8-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ramips-mt76x8
      id: asset-d8e4b3ee916e1a1e1ae173c4fc2a2153
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ramips-mt76x8.zip
        asset_name: x-wrt-25.04_b202504130929-ramips-mt76x8.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504130929-ramips-mt76x8-nosymbol
      id: asset-f26dfad9914e132771ae9a03adf710e8
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-ramips-mt76x8-nosymbol.zip
        asset_name: x-wrt-25.04_b202504130929-ramips-mt76x8-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-rockchip-armv8_armsr-armv8:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="rockchip-armv8 armsr-armv8" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-rockchip-armv8_armsr-armv8
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-rockchip-armv8
      id: asset-e96bfd8f866ac5437b5ec2a28e686393
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-rockchip-armv8.zip
        asset_name: x-wrt-25.04_b202504130929-rockchip-armv8.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504130929-armsr-armv8
      id: asset-9452ac80bc94c559b4ca0bf814c4c99b
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-armsr-armv8.zip
        asset_name: x-wrt-25.04_b202504130929-armsr-armv8.zip
        asset_content_type: application/zip
        overwrite: true
  build-x86_64:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="x86_64" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-x86_64
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-x86_64
      id: asset-e497dd670e16fc9ecc6e4a6d3c15c29d
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-x86_64.zip
        asset_name: x-wrt-25.04_b202504130929-x86_64.zip
        asset_content_type: application/zip
        overwrite: true
  build-x86_64-docker:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="x86_64-docker" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-x86_64-docker
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504130929-x86_64-docker
      id: asset-9a21acc138700e7b7e558655439d34f7
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504130929-x86_64-docker.zip
        asset_name: x-wrt-25.04_b202504130929-x86_64-docker.zip
        asset_content_type: application/zip
        overwrite: true
