#=================================================
#   Description: Build X-WRT using GitHub Actions
#   Lisence: MIT
#   Author: ptpt52
#=================================================

name: Build Jobs 25.04_b202504211319

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Create Github Release
    if: contains(github.ref, 'tags/v')
    runs-on: ubuntu-24.04
    steps:
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
        name: X-WRT ${{ github.ref_name }}
        draft: false
        allowUpdates: true
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v4
      with:
        name: release_url
        path: release_url.txt
  build-ath79-generic_ath79-generic-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ath79-generic ath79-generic-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ath79-generic_ath79-generic-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ath79-generic
      id: asset-c1f319a46e52ad8f1f1a682c013c44e4
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ath79-generic.zip
        asset_name: x-wrt-25.04_b202504211319-ath79-generic.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ath79-generic-nosymbol
      id: asset-5836a90304b568f9bef77b2976b3a8e8
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ath79-generic-nosymbol.zip
        asset_name: x-wrt-25.04_b202504211319-ath79-generic-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-ath79-nand:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ath79-nand" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ath79-nand
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ath79-nand
      id: asset-7a4e2acd3feafdb51004ae458e030e4e
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ath79-nand.zip
        asset_name: x-wrt-25.04_b202504211319-ath79-nand.zip
        asset_content_type: application/zip
        overwrite: true
  build-ipq40xx-generic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ipq40xx-generic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ipq40xx-generic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ipq40xx-generic
      id: asset-b0b9ea31547728210628d49ed377270e
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ipq40xx-generic.zip
        asset_name: x-wrt-25.04_b202504211319-ipq40xx-generic.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2709:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2709" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2709
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-bcm27xx-bcm2709
      id: asset-dff880c02569b842d7289d80dd96380b
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-bcm27xx-bcm2709.zip
        asset_name: x-wrt-25.04_b202504211319-bcm27xx-bcm2709.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2710:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2710" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2710
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-bcm27xx-bcm2710
      id: asset-a746f083bec826d2727603cef5072448
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-bcm27xx-bcm2710.zip
        asset_name: x-wrt-25.04_b202504211319-bcm27xx-bcm2710.zip
        asset_content_type: application/zip
        overwrite: true
  build-mediatek-mt7622:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mediatek-mt7622" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mediatek-mt7622
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-mediatek-mt7622
      id: asset-fa95b26984b639185dfc63009514cb9e
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-mediatek-mt7622.zip
        asset_name: x-wrt-25.04_b202504211319-mediatek-mt7622.zip
        asset_content_type: application/zip
        overwrite: true
  build-mediatek-filogic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mediatek-filogic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mediatek-filogic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-mediatek-filogic
      id: asset-8cfd15ce74d087485a707a72942fd581
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-mediatek-filogic.zip
        asset_name: x-wrt-25.04_b202504211319-mediatek-filogic.zip
        asset_content_type: application/zip
        overwrite: true
  build-mediatek-filogic-uncommon:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mediatek-filogic-uncommon" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mediatek-filogic-uncommon
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-mediatek-filogic-uncommon
      id: asset-8fa255fa967a48b273a04ce784ed9bcb
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-mediatek-filogic-uncommon.zip
        asset_name: x-wrt-25.04_b202504211319-mediatek-filogic-uncommon.zip
        asset_content_type: application/zip
        overwrite: true
  build-qualcommax-ipq807x_qualcommax-ipq60xx_qualcommax-ipq50xx:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="qualcommax-ipq807x qualcommax-ipq60xx qualcommax-ipq50xx" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-qualcommax-ipq807x_qualcommax-ipq60xx_qualcommax-ipq50xx
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-qualcommax-ipq807x
      id: asset-ec3467b4cf60fa98a18481d989a64e7f
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-qualcommax-ipq807x.zip
        asset_name: x-wrt-25.04_b202504211319-qualcommax-ipq807x.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504211319-qualcommax-ipq60xx
      id: asset-98b1c75e6b12c9607e782839777e92ca
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-qualcommax-ipq60xx.zip
        asset_name: x-wrt-25.04_b202504211319-qualcommax-ipq60xx.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504211319-qualcommax-ipq50xx
      id: asset-f74e40317e92a1ab270d8ef07e9bc46f
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-qualcommax-ipq50xx.zip
        asset_name: x-wrt-25.04_b202504211319-qualcommax-ipq50xx.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2711:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2711" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2711
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-bcm27xx-bcm2711
      id: asset-4d705b1ac638211442365e9c0b6ea95b
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-bcm27xx-bcm2711.zip
        asset_name: x-wrt-25.04_b202504211319-bcm27xx-bcm2711.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm27xx-bcm2712:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm27xx-bcm2712" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm27xx-bcm2712
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-bcm27xx-bcm2712
      id: asset-4f3830b55b6ff33f5b23ebe50b496a29
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-bcm27xx-bcm2712.zip
        asset_name: x-wrt-25.04_b202504211319-bcm27xx-bcm2712.zip
        asset_content_type: application/zip
        overwrite: true
  build-bcm53xx-generic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="bcm53xx-generic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-bcm53xx-generic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-bcm53xx-generic
      id: asset-815f820c611ce31d18922abb7d42c928
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-bcm53xx-generic.zip
        asset_name: x-wrt-25.04_b202504211319-bcm53xx-generic.zip
        asset_content_type: application/zip
        overwrite: true
  build-ipq806x-generic:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ipq806x-generic" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ipq806x-generic
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ipq806x-generic
      id: asset-b00e0a3ce7b2f132512c28e14ff6f1aa
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ipq806x-generic.zip
        asset_name: x-wrt-25.04_b202504211319-ipq806x-generic.zip
        asset_content_type: application/zip
        overwrite: true
  build-mvebu-cortexa9:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="mvebu-cortexa9" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-mvebu-cortexa9
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-mvebu-cortexa9
      id: asset-de1aebe58b202e54403221f4acf4606a
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-mvebu-cortexa9.zip
        asset_name: x-wrt-25.04_b202504211319-mvebu-cortexa9.zip
        asset_content_type: application/zip
        overwrite: true
  build-ramips-mt7620_ramips-mt7620-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ramips-mt7620 ramips-mt7620-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ramips-mt7620_ramips-mt7620-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ramips-mt7620
      id: asset-b9ec0c32fdd238834c5fae2b126cbba5
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ramips-mt7620.zip
        asset_name: x-wrt-25.04_b202504211319-ramips-mt7620.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ramips-mt7620-nosymbol
      id: asset-f10a0079252a68d26c2d17e4de9f8cf4
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ramips-mt7620-nosymbol.zip
        asset_name: x-wrt-25.04_b202504211319-ramips-mt7620-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-ramips-mt7621_ramips-mt7621-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ramips-mt7621 ramips-mt7621-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ramips-mt7621_ramips-mt7621-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ramips-mt7621
      id: asset-8f1e7e770d3ad278f3ae9a438e2e535e
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ramips-mt7621.zip
        asset_name: x-wrt-25.04_b202504211319-ramips-mt7621.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ramips-mt7621-nosymbol
      id: asset-e70f4fdc15619724fcf1dc561ba3099c
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ramips-mt7621-nosymbol.zip
        asset_name: x-wrt-25.04_b202504211319-ramips-mt7621-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-ramips-mt76x8_ramips-mt76x8-nosymbol:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="ramips-mt76x8 ramips-mt76x8-nosymbol" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-ramips-mt76x8_ramips-mt76x8-nosymbol
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ramips-mt76x8
      id: asset-cf8c2835a2f211a3bd6d2a1a5b3ec165
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ramips-mt76x8.zip
        asset_name: x-wrt-25.04_b202504211319-ramips-mt76x8.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504211319-ramips-mt76x8-nosymbol
      id: asset-7f7a9662b1cce102af28f2642a8d523b
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-ramips-mt76x8-nosymbol.zip
        asset_name: x-wrt-25.04_b202504211319-ramips-mt76x8-nosymbol.zip
        asset_content_type: application/zip
        overwrite: true
  build-rockchip-armv8_armsr-armv8:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="rockchip-armv8 armsr-armv8" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-rockchip-armv8_armsr-armv8
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-rockchip-armv8
      id: asset-842d33d2e9bac5f4c489e2fbd397f045
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-rockchip-armv8.zip
        asset_name: x-wrt-25.04_b202504211319-rockchip-armv8.zip
        asset_content_type: application/zip
        overwrite: true
    - name: Upload Release Asset x-wrt-25.04_b202504211319-armsr-armv8
      id: asset-238fae81398debe1782cbda8dec36293
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-armsr-armv8.zip
        asset_name: x-wrt-25.04_b202504211319-armsr-armv8.zip
        asset_content_type: application/zip
        overwrite: true
  build-x86_64:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="x86_64" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-x86_64
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-x86_64
      id: asset-e69fc36f14d2752d9400106c88d9e9c2
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-x86_64.zip
        asset_name: x-wrt-25.04_b202504211319-x86_64.zip
        asset_content_type: application/zip
        overwrite: true
  build-x86_64-docker:
    if: contains(github.ref, 'tags/v')
    needs: release
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Pre Initialization environment
      run: |
        docker rmi `docker images -q` || true
        sudo -E df -h
        sudo ls -lh /mnt
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler tzdata python3-pyelftools python3-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clean up disk
      run: sudo rm -rf /opt/*
    - name: Clone source code
      run: |
        sudo -E mkdir /mnt/work
        sudo -E chmod 777 /mnt/work
        git clone --depth 1 --branch `cat release.tag` https://github.com/x-wrt/x-wrt.git /mnt/work/x-wrt
    - name: Update feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds update -a
    - name: Install feeds
      run: cd /mnt/work/x-wrt && ./scripts/feeds install -a
    - name: Building
      run: |
        cp *.sh /mnt/work/x-wrt/
        cp release.tag /mnt/work/x-wrt/
        cd /mnt/work/x-wrt
        echo -e "$(nproc) thread build."
        BTARGET="x86_64-docker" sh build.sh $(nproc)
    - name : Upload make.log if failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-failure-log-x86_64-docker
        path: make.log
    - name: Load Release URL File from release job
      uses: actions/download-artifact@v4
      with:
        name: release_url
        path: release_url
    - name: Get Release Upload URL
      id: get_release_info
      run: |
        value=`cat release_url/release_url.txt || cat release_url.txt`
        echo "upload_url=$value" >> $GITHUB_OUTPUT
      env:
        TAG_REF_NAME: ${{ github.ref }}
        REPOSITORY_NAME: ${{ github.repository }}
    - name: Upload Release Asset x-wrt-25.04_b202504211319-x86_64-docker
      id: asset-ccdd9cf8a4f47997d89954c5febff946
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        github_token: ${{ secrets.WORKFLOW_TOKEN }}
        upload_url: ${{ steps.get_release_info.outputs.upload_url }}
        asset_path: /mnt/work/x-wrt/x-wrt-25.04_b202504211319-x86_64-docker.zip
        asset_name: x-wrt-25.04_b202504211319-x86_64-docker.zip
        asset_content_type: application/zip
        overwrite: true
